
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from PageObjects.Swift_FieldInterview import SwiftFieldInterview
from PageObjects.Swift_Login import SwiftLogin
from Utilities.readProperties import ReadConfig
from Utilities.Logger import LogGenerator


class Test_FieldInterview_TC:
    baseURL = ReadConfig.getURL()
    username = ReadConfig.getUseremail()
    password = ReadConfig.getPassword()
    logger = LogGenerator.logenerator()

    def test_fieldInterview(self):
        self.driver = webdriver.Chrome()
        self.driver.get(self.baseURL)
        self.driver.maximize_window()
        self.swftLogin = SwiftLogin(self.driver)
        self.driver.implicitly_wait(30)
        self.swftLogin.setUsername(self.username)
        self.swftLogin.setPassword(self.password)
        self.swftLogin.login()
        self.swftLogin.dismissAlert()
        self.logger.info("SWIFT PROTECT -> FIELD INTERVIEW TEST INITIATED")
        self.title_name = self.driver.title
        print("Title name -> "+self.title_name+" Login Successful")
        self.FI = SwiftFieldInterview(self.driver, WebDriverWait)
        self.driver.implicitly_wait(20)
        self.FI.clickAgencyRecords()
        self.FI.clickFieldInterviews()
        self.FI.getTitle1()
        print("Field Interview Page Opened")
        self.FI.clickNewFIbutton()
        self.FI.setFiInterviewdata("04/20/2023")
        self.FI.setFiBusinessname("RedSpeck Solution Test 2")
        self.FI.setFiUnitnum()
        self.FI.closeAlert1()
        self.FI.setFiAddress("Tansi Nagar")
        self.FI.setFiState("TN")
        self.FI.setFiStreetName("anna nagar")
        self.FI.setFiCity("Chennai")
        self.FI.setFiZip("123456789")
        self.FI.setFiTxtEditor("Jane Smith was found guilty.")
        self.FI.clickFiSave()
        self.FI.disableGoogleprompt()
        self.logger.info("SWIFT PROTECT -> FIELD INTERVIEW PAGE DATA SUCCESSFULLY ENTERED")
        self.FI.switchToSubjectDetails()
        self.FI.clickNewDetails()
        self.FI.addWithout_MNI()
        self.FI.setFiSubjectCode()
        self.FI.setFiFirstname("Jack")
        self.FI.setFiSSNnumber("123456789")
        self.FI.setFiLastname("Anderson")
        self.FI.setFiMiddlename("Williams")
        self.FI.setFiAlertnotes("Nil")
        self.FI.setFiComment("Jack is guilty")
        self.logger.info("SWIFT PROTECT -> SUBJECT DETAILS DATA SUCCESSFULLY ENTERED")
        self.FI.switchToOtherdetails()
        self.FI.setFiResStatus("R")
        self.FI.setFiDOB("04/20/1988")
        self.FI.setFiSex("M")
        self.FI.setFiDrivngLicn("S-514-778-616-977")
        self.FI.setFiEthnicty("H")
        self.FI.setFiWeightMin("65")
        self.FI.setFiWeightMax("75")
        self.FI.setFiHaircolor("BRN")
        self.FI.setFiHairLen("ME")
        self.FI.setFiComplexn("OLV")
        self.FI.setFiAttire("2")
        self.FI.setFiScartchn()
        self.FI.setFiType()
        self.FI.setFiOthrResStatus("Resident")
        self.FI.setFiAgeMin("25")
        self.FI.setfiAgemax("45")
        self.FI.setFiDriLicState("MA")
        self.FI.setFiRace("I")
        self.FI.setFiHeightFtMin("5")
        self.FI.setFiHeighInMin("11")
        self.FI.setFiHeightFtMax("6")
        self.FI.setFiHeighInMax("2")
        self.FI.setFiEyecolor("BRO")
        self.FI.setFiHairStyle("144|17")
        self.FI.setFiFacialHair("26|2")
        self.FI.setFiBuild("U")
        self.FI.setFiTeeth("11")
        self.logger.info("SWIFT PROTECT -> OTHER DETAILS DATA SUCCESSFULLY ENTERED")
        self.FI.switchToAddress()
        self.FI.setFiStreetname("George Street")
        self.FI.setFiSubCity()
        self.FI.clickAlert3()
        self.FI.setFiSubCity1("Texas")
        self.FI.setFiSubZip("1284756892")
        self.FI.setFiCellnum("1219374657")
        self.FI.setFiEmail("jack@gmail.com")
        self.FI.setFiUnitNumber("Spring Field")
        self.FI.setFiSubState("MA")
        self.FI.setFiHomeNumber("1214564758")
        self.FI.setFiWorkNumber("0109274726")
        self.logger.info("SWIFT PROTECT -> ADDRESS DATA SUCCESSFULLY ENTERED")
        self.FI.switchToVehicleDetails()
        self.FI.setFiPlateNum("6476")
        self.FI.setFiOccupant()
        self.FI.clickAlert4()
        self.FI.setFiOccupant1("Working")
        self.FI.setFiMakeID("A")
        self.FI.setFiMakeID1()
        self.FI.setFiMakeIDSelect()
        self.FI.setFiStyleChosen()
        self.FI.setFiStyleSelect()
        self.FI.setFiButtomColor()
        self.FI.setFiButtomSelect()
        self.FI.setFiVehicleYear("2015")
        self.FI.setFiTopcolor()
        self.FI.setFiTopcolorSelect()
        self.FI.setFiPlateState("KS")
        self.logger.info("SWIFT PROTECT -> VEHICLE DATA SUCCESSFULLY ENTERED")
        self.FI.setFiFinalButSave()
        self.FI.setFiSuccessMsg()
        print("Data's Saved")








